### ISSUE TITLE
cannot install with pip: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by dchimeno** [anthill/Python_OpeningHours#9]
pip install opening_hours
```
Collecting opening_hours
  Downloading https://files.pythonhosted.org/packages/25/45/9a15b4c8b2901a78f72b071ad050bfc0d98adc9e0b1ecb9afc79f0750dc3/opening_hours-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dp/y2d6qpg93pbfglz0vtrt7dqc0000gq/T/pip-install-82bfx27x/opening-hours/setup.py", line 12
        if (call(["make", "-C", "C_OpeningHours", "install"])):
                                                              ^
    TabError: inconsistent use of tabs and spaces in indentation
````

**Comment by vcschapp** [comment]
I'm unable to install the library due to this issue... Any chance it will be fixed?

**Comment by martin3000** [comment]
I think it worked in python2, in python3 it does not work because of inconsistent indentations.
